import type { V3 } from '../worldConfig'
export type Stop={id:string;name:[string,string];position:V3;camera:V3;action:[string,string];detail:[string,string]}
export const STOPS:Record<string,Stop[]>={
 chongzhen:[{id:'pending-studio',name:['交流室','Exchange room'],position:[0,1.4,-1.6],camera:[0,5,16],action:['点亮交流室 · 发出灵感艇','Light the room · Launch idea boat'],detail:['围绕多 Agent 内容产品与 AI 辅助设计交流。项目细节待补充。灵感艇仅表示个人持续交流。','A place for multi-agent content and AI-assisted design. Details are to be added. The boat represents personal exchanges.']}],
 opensource:[{id:'dsh-lark-bridge',name:['飞书桥接枝干','Lark bridge branch'],position:[-4.9,.5,3.1],camera:[-15,5,17],action:['点亮枝干 · 消息舱靠站','Light branch · Dock message pod'],detail:['让飞书成为 Agent 的原生前端。','Making Lark a native front end for agents.']},{id:'trae-to-lark',name:['TRAE 连接枝干','TRAE connection branch'],position:[5.2,.5,2.4],camera:[17,5,15],action:['沿连接路径送达消息','Send a message along the connection'],detail:['飞书桥接 TRAE、Claude Code 与 Codex CLI。','Bridging Lark with TRAE, Claude Code and Codex CLI.']}],
 bytedance:[{id:'material-gen-agent',name:['创作台','Creation desk'],position:[-5.5,1,4.7],camera:[-15,10,19],action:['派送创作任务','Dispatch creation task'],detail:['业务 SOP → Skill → Harness → 垂类 Agent。','Business SOP → Skill → Harness → domain agent.']},{id:'material-qc-agent',name:['检查廊','Quality corridor'],position:[5.4,.5,4.7],camera:[16,9,18],action:['送入质量检查廊','Route to quality check'],detail:['规则与模型结合的多场景判断。','Rules and model judgments across multiple scenarios.']},{id:'audit-model-migration',name:['比较调优台','Comparison lab'],position:[5.6,2.8,-3.4],camera:[18,10,-12],action:['比较两条模型路径','Compare model paths'],detail:['模型迁移、归因与质量治理。','Model migration, analysis and quality governance.']},{id:'multimodal-audit-workflow',name:['证据汇合区','Evidence junction'],position:[-4.8,3.2,-4.5],camera:[-17,12,-14],action:['汇合多种证据','Merge evidence streams'],detail:['文本、图片与商品证据的空间隐喻。','A spatial metaphor for text, images and product evidence.']},{id:'performance-qc',name:['复核分流区','Review routing'],position:[.5,4,-6.5],camera:[2,12,-20],action:['分流一致与待复核任务','Route agreement and review tasks'],detail:['人机一致自动审，不一致回人工。','Automatic approval on agreement; human review otherwise.']}],
 hyundai:[{id:'ai-music-wallpaper',name:['IONIQ V 音乐座舱','IONIQ V music cockpit'],position:[3.25,7.3,.5],camera:[11,11,15],action:['跟车前往座舱','Follow the car to the cockpit'],detail:['烟台实习 · AI 音乐壁纸。造车环境是叙事意象，非个人制造成果。车型与内饰为简化概念表达。','Yantai internship · AI Music Wallpaper. Manufacturing is a visual narrative, not a personal achievement. Vehicle and cabin are simplified concepts.']}],
 university:[{id:'dut-digital-human',name:['数字人实验室','Digital human lab'],position:[-3.6,.1,8.3],camera:[-10,3,20],action:['唤醒数字人屏幕','Wake the digital human screen'],detail:['大模型 API、语音交互与 UE5 Demo。','LLM APIs, voice interaction and a UE5 demo.']},{id:'dut-basketball',name:['校园篮球场','Campus basketball'],position:[-7.2,2.2,1.3],camera:[-20,10,7],action:['沿步道发现球场','Discover the court along the path'],detail:['篮球赛经历；角色、赛程与结果待补充。','A basketball experience; role, schedule and results to be added.']},{id:'dut-theater',name:['《屈伯川》小剧场','Qu Bochuan theater'],position:[4.4,-2.6,7.7],camera:[13,1,19],action:['点亮空舞台','Light the empty stage'],detail:['校史话剧《屈伯川》；具体参与细节待补充。','The university history play Qu Bochuan; participation details to be added.']}]
}
export const THEMES:Record<string,[string,string]>={chongzhen:['崇振创想港','Chongzhen creative harbor'],opensource:['开源能力树城','Open-source capability tree'],bytedance:['字节立体枢纽城','ByteDance dispatch city'],hyundai:['海岸造车与音乐体验','Coastal driving & music'],university:['凌水校园与三段故事','Lingshui campus & three stories']}
export const WORLD_SCALE:Record<string,number>={university:4.5,bytedance:4.6,opensource:4.65,hyundai:3.4,chongzhen:3.8}
