import {useMemo,useRef,type MutableRefObject} from 'react'
import {useGLTF,useTexture} from '@react-three/drei'
import {useFrame} from '@react-three/fiber'
import * as T from 'three'
import {useSpace} from '../state'
import WorldSigns from './WorldSigns'
import MotorSurfaceLights from './MotorSurfaceLights'
import {ProjectPath} from './WorldEffects'
import {STOPS} from './catalog'
import {HUB_TRACKS} from './builders/hub'
import {motorRoad} from './builders/motor'
const vertex=`varying vec2 v;void main(){v=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`
function Sign({id}:{id:string}){const map=useTexture(`${import.meta.env.BASE_URL}models/worlds/${id==='university'?'dut-official-vi.png':'hyundai-ci.jpg'}`);return <mesh position={id==='university'?[-1.65,5.06,5.38]:[-3.9,5.23,7.11]}><planeGeometry args={id==='university'?[.91,.91]:[4.3,.7]}/><shaderMaterial uniforms={{map:{value:map},dut:{value:id==='university'?1:0}}} vertexShader={vertex} fragmentShader={`varying vec2 v;uniform sampler2D map;uniform float dut;void main(){vec2 uv=dut>.5?vec2(.37+v.x*.29,.535+v.y*.275):vec2(.06+v.x*.88,.37+v.y*.26);vec3 c=texture2D(map,uv).rgb;gl_FragColor=vec4(c,1.);}`}/></mesh>}
function Shell(){return <mesh raycast={()=>{}}><sphereGeometry args={[10.05,48,32]}/><shaderMaterial transparent depthWrite={false} side={T.FrontSide} blending={T.AdditiveBlending} vertexShader={`varying vec3 n;varying vec3 eye;void main(){vec4 mv=modelViewMatrix*vec4(position,1.);n=normalize(normalMatrix*normal);eye=normalize(-mv.xyz);gl_Position=projectionMatrix*mv;}`} fragmentShader={`varying vec3 n;varying vec3 eye;void main(){float f=pow(1.-abs(dot(normalize(n),normalize(eye))),4.5);gl_FragColor=vec4(.14,.65,.5,f*.48);}`}/></mesh>}
export default function DesignedModel({id,selected=null,action=0,paused=false,near=true,follow}:{id:string;selected?:string|null;action?:number;paused?:boolean;near?:boolean;follow?:MutableRefObject<number|null>}){
 const low=useSpace(s=>s.low)
 const {scene}=useGLTF(`${import.meta.env.BASE_URL}models/worlds/${id}${near&&!low?'':'-low'}.glb?v=refined-worlds-1`),model=useMemo(()=>{const copy=scene.clone(true);const mats=new Map<T.Material,T.Material>();copy.traverse(o=>{if(o instanceof T.Mesh){const old=o.material as T.Material;if(!mats.has(old))mats.set(old,old.clone());o.material=mats.get(old)!;o.castShadow=true;o.receiveShadow=true}});return copy},[scene]),time=useRef(0),effect=useRef(0),lastAction=useRef(action),screen=useMemo(()=>({time:{value:0},signalOn:{value:0}}),[]),space=useSpace()
 const path=useMemo(()=>new T.CatmullRomCurve3(motorRoad.map(q=>new T.Vector3(...q)),true),[])
 const motion=useMemo(()=>{const map=new Map<string,T.Object3D>();model.traverse(o=>{if(/^(motor_car_|motor_arm_|harbor_boat|harbor_arm|tree_lift|tree_pod_|hub_shuttle_|hub_dispatch|campus_ball)/.test(o.name))map.set(o.name,o)});return map},[model])
 const stop=STOPS[id].find(s=>s.id===selected),pulse=useRef<T.Mesh>(null)
 useFrame((_,dt)=>{if(lastAction.current!==action){lastAction.current=action;effect.current=0}if(!paused&&!space.reduced&&!document.hidden){time.current+=Math.min(dt,.05)*(near?1:.15);effect.current+=Math.min(dt,.05)}const t=time.current,e=effect.current;screen.time.value=t;screen.signalOn.value=selected?1:0;if(pulse.current)pulse.current.scale.setScalar(1+Math.sin(t*2)*.04)
 motion.forEach((o,name)=>{if(name.startsWith('motor_car_')){const i=Number(name[name.length-1]),f=i===0&&follow?.current!==null&&follow?.current!==undefined?follow.current:(t*.022+i/3)%1;o.position.copy(path.getPoint(f));const d=path.getTangent(f);o.rotation.set(-Math.atan2(d.y,Math.hypot(d.x,d.z)),Math.atan2(d.x,d.z),0,'YXZ')}else if(name.startsWith('motor_arm_')||name==='harbor_arm'){o.rotation.y=Math.sin(t*.55)*.17}else if(name==='harbor_boat'){const trip=selected&&action>0?Math.sin(Math.min(1,e/12)*Math.PI)*9:0;o.position.set(Math.sin(t*.15)*.85+trip,-.18,3.6+Math.cos(t*.15)*.35+trip*.3);o.rotation.y=trip>0?Math.PI/2:t*.15+Math.PI/2}else if(name==='tree_lift'){o.position.y=-5.3+(Math.sin(t*.16)+1)*4.1}else if(name.startsWith('tree_pod_')){const sign=name.endsWith('0')?-1:1,f=selected?Math.min(1,e/3):(.5+.5*Math.sin(t*.17));o.position.set(sign*(7-f*2),.7,5-f*2);o.rotation.y=sign*-.9}else if(name.startsWith('hub_shuttle_')){const i=Number(name[name.length-1]),a=t*.16+i*2.094,r=HUB_TRACKS[i%2][0];const target=stop?new T.Vector3(...stop.position):null;if(target&&selected){o.position.lerpVectors(new T.Vector3(0,2.4,0),target,Math.min(1,Math.max(0,(e-i*.7)/2.4)));o.position.y+=.6+i*.16}else{o.position.set(Math.sin(a)*r,HUB_TRACKS[i%2][1]+Math.sin(a)*.65+.18,Math.cos(a)*r);o.rotation.y=a+Math.PI/2}}else if(name==='hub_dispatch'){o.rotation.y=selected?Math.sin(Math.min(e,2.4)*.6)*.15:t*.07}else if(name==='campus_ball'){o.position.y=selected==='dut-basketball'?2.15+Math.abs(Math.sin(t*2.5))*.6:2.15}})
 })
 return <group><primitive object={model}/><WorldSigns id={id}/>{id==='hyundai'&&<MotorSurfaceLights near={near}/>}<ProjectPath id={id} stop={stop||null}/>{near&&selected&&<pointLight position={id==='university'?[4.4,-1.2,6]:id==='chongzhen'?[0,2,-1.6]:[0,2,0]} color={id==='opensource'?'#8ae7bb':'#ffcf8d'} intensity={12} distance={8} decay={2}/>}{id==='opensource'&&<Shell/>}{(id==='university'||id==='hyundai')&&<Sign id={id}/>}
 {stop&&id!=='hyundai'&&<mesh ref={pulse} position={stop.position} rotation={[-Math.PI/2,0,0]}><torusGeometry args={[.7,.035,6,40]}/><meshBasicMaterial color={id==='chongzhen'?'#ffc77a':'#83d9ff'} toneMapped={false}/></mesh>}
 {id==='university'&&<><mesh position={[-4.4,.15,5.41]}><planeGeometry args={[1.5,2.7]}/><shaderMaterial uniforms={screen} vertexShader={vertex} fragmentShader={`varying vec2 v;uniform float time;uniform float signalOn;void main(){vec2 p=v-.5;float head=1.-smoothstep(.065,.08,length(p-vec2(0.,.29)));float body=(1.-smoothstep(.1,.12,abs(p.x)))*step(-.16,p.y)*step(p.y,.18);float legs=(1.-smoothstep(.027,.04,abs(abs(p.x)-.06)))*step(-.44,p.y)*step(p.y,-.14);float grid=.4+.6*step(.8,fract(v.y*65.-time*.7));gl_FragColor=vec4(vec3(.04,.24,.4)+vec3(.1,.7,1.)*(head+body+legs)*grid*(.4+signalOn*.6),1.);}`}/></mesh><group position={[2.5,0,-5.5]}>{Array.from({length:13},(_,i)=><sprite key={i} position={[Math.sin(i*.7)*4.5,1+(i%4)*1.8,Math.cos(i*.7)*2.5]} scale={[7,6,1]}><shaderMaterial transparent depthWrite={false} vertexShader={`varying vec2 v;void main(){v=uv;vec4 mv=modelViewMatrix*vec4(0.,0.,0.,1.);mv.xy+=position.xy*vec2(length(modelMatrix[0].xyz),length(modelMatrix[1].xyz));gl_Position=projectionMatrix*mv;}`} fragmentShader={`varying vec2 v;void main(){float r=length((v-.5)*2.);float a=pow(max(0.,1.-r*r),2.)*.17;gl_FragColor=vec4(.68,.78,.88,a);}`}/></sprite>)}</group></>}
 {id==='hyundai'&&<mesh position={[3.25,7.45,-.909]}><planeGeometry args={[2.23,.4]}/><shaderMaterial uniforms={screen} vertexShader={vertex} fragmentShader={`varying vec2 v;uniform float time;void main(){float wave=.5+sin(v.x*18.-time)*.25*sin(v.x*3.14159);float a=exp(-abs(v.y-wave)*40.);gl_FragColor=vec4(vec3(.005,.02,.06)+vec3(.12,.5,1.)*a,1.);}`}/></mesh>}
 </group>
}
