import {useEffect,useMemo,useRef,type MutableRefObject} from 'react'
import {useGLTF,useTexture} from '@react-three/drei'
import {useFrame} from '@react-three/fiber'
import * as T from 'three'
import {useSpace} from '../state'
import WorldSigns from './WorldSigns'
import CampusMist from './CampusMist'
import HarborRefined from './HarborRefined'
import HubRefined from './HubRefined'
import {treeLiftY,treePodPose} from './treeMotionV2'
import {useRefinedWorldSurfaces,applyRefinedWorldSurface} from './useRefinedWorldSurfaces'
import MotorSurfaceLights from './MotorSurfaceLights'
import {ProjectPath} from './WorldEffects'
import {mainWorldRevision,stopsForRevision,type ModelRevision} from './modelRevisions'
import {HUB_TRACKS} from './builders/hub'
import {motorRoad} from './builders/motor'
import {MUSIC_SCREEN,musicOverlayLocal,FACTORY_LOGO,factoryLogoFaceLocal,motorRoadV2,FACTORY_YAW,factoryPoint,cockpitPoint,FACTORY_SCALE,COCKPIT_SCALE,MOTOR_RIDE_HEIGHT} from './motorMotionV2'
import {campusRoomPose} from './campusSurfaceV2'
const vertex=`varying vec2 v;void main(){v=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`
function Sign({id,v2=false}:{id:string;v2?:boolean}){const map=useTexture(`${import.meta.env.BASE_URL}models/worlds/${id==='university'?'dut-official-vi.png':'hyundai-ci.jpg'}`);return <mesh position={id==='university'?[-1.65,5.06,5.38]:v2?factoryPoint(factoryLogoFaceLocal):[-3.9,5.23,7.11]} rotation={[0,id==='hyundai'&&v2?FACTORY_YAW:0,0]}><planeGeometry args={id==='university'?[.91,.91]:v2?[FACTORY_LOGO.size[0]*FACTORY_SCALE[0],FACTORY_LOGO.size[1]*FACTORY_SCALE[1]]:[4.3,.7]}/><shaderMaterial uniforms={{map:{value:map},dut:{value:id==='university'?1:0}}} vertexShader={vertex} fragmentShader={`varying vec2 v;uniform sampler2D map;uniform float dut;void main(){vec2 uv=dut>.5?vec2(.37+v.x*.29,.535+v.y*.275):vec2(.06+v.x*.88,.37+v.y*.26);vec3 c=texture2D(map,uv).rgb;gl_FragColor=vec4(c,1.);}`}/></mesh>}
function Shell(){return <mesh raycast={()=>{}}><sphereGeometry args={[10.05,48,32]}/><shaderMaterial transparent depthWrite={false} side={T.FrontSide} blending={T.AdditiveBlending} vertexShader={`varying vec3 n;varying vec3 eye;void main(){vec4 mv=modelViewMatrix*vec4(position,1.);n=normalize(normalMatrix*normal);eye=normalize(-mv.xyz);gl_Position=projectionMatrix*mv;}`} fragmentShader={`varying vec3 n;varying vec3 eye;void main(){float f=pow(1.-abs(dot(normalize(n),normalize(eye))),4.5);gl_FragColor=vec4(.14,.65,.5,f*.48);}`}/></mesh>}
export function LegacyModel({id,candidate=false,revision=candidate?'v2':'original',selected=null,action=0,paused=false,near=true,follow}:{id:string;selected?:string|null;action?:number;paused?:boolean;near?:boolean;follow?:MutableRefObject<number|null>;candidate?:boolean;revision?:ModelRevision}){
 const low=useSpace(s=>s.low),{maps:surfaceMaps,environment}=useRefinedWorldSurfaces(),v2=revision==='v2',refined=revision!=='original'
 const {scene}=useGLTF(`${import.meta.env.BASE_URL}models/worlds/${id}${refined?'-refined-'+revision:''}${near&&!low?'':'-low'}.glb?v=refined-worlds-20260927-visual1`),model=useMemo(()=>{const copy=scene.clone(true);const mats=new Map<T.Material,T.Material>();copy.traverse(o=>{if(o instanceof T.Mesh){const old=o.material as T.Material;if(!mats.has(old)){const owned=old.clone();if(refined&&near&&!low)applyRefinedWorldSurface(owned,surfaceMaps,environment);mats.set(old,owned)}o.material=mats.get(old)!;o.castShadow=!o.material.transparent;o.receiveShadow=true}});return copy},[scene,refined,near,low,surfaceMaps,environment]),time=useRef(0),effect=useRef(0),lastAction=useRef(action),screen=useMemo(()=>({time:{value:0},signalOn:{value:0}}),[]),space=useSpace()
 useEffect(()=>()=>{const materials=new Set<T.Material>();model.traverse(o=>{if(o instanceof T.Mesh){const list=Array.isArray(o.material)?o.material:[o.material];list.forEach(m=>materials.add(m))}});materials.forEach(m=>m.dispose())},[model])
 const path=useMemo(()=>new T.CatmullRomCurve3((v2?motorRoadV2:motorRoad).map(q=>new T.Vector3(...q)),true),[v2])
 const humanPose=campusRoomPose(-4.4,.15,5.3,-3.6,7.91);humanPose.position[0]+=Math.sin(humanPose.yaw)*.11;humanPose.position[2]+=Math.cos(humanPose.yaw)*.11

 const motion=useMemo(()=>{const map=new Map<string,T.Object3D>();model.traverse(o=>{if(/^(motor_car_|motor_arm_|harbor_boat|harbor_arm|tree_lift|tree_pod_|hub_shuttle_|hub_dispatch|campus_ball)/.test(o.name))map.set(o.name,o)});return map},[model])
 const stop=stopsForRevision(id,revision).find(s=>s.id===selected),pulse=useRef<T.Mesh>(null)
 useFrame((_,dt)=>{if(lastAction.current!==action){lastAction.current=action;effect.current=0}if(!paused&&!space.reduced&&!document.hidden){time.current+=Math.min(dt,.05)*(near?1:.15);effect.current+=Math.min(dt,.05)}const t=time.current,e=effect.current;screen.time.value=t;screen.signalOn.value=selected?1:0;if(pulse.current)pulse.current.scale.setScalar(1+Math.sin(t*2)*.04)
 motion.forEach((o,name)=>{if(name.startsWith('motor_car_')){const i=Number(name[name.length-1]),f=i===0&&follow?.current!==null&&follow?.current!==undefined?follow.current:(t*.022+i/3)%1;o.position.copy(path.getPoint(f));if(v2)o.position.y+=MOTOR_RIDE_HEIGHT;const d=path.getTangent(f);o.rotation.set(-Math.atan2(d.y,Math.hypot(d.x,d.z)),Math.atan2(d.x,d.z),0,'YXZ')}else if(name.startsWith('motor_arm_')||name==='harbor_arm'){o.rotation.y=(v2&&name.startsWith('motor_arm_')?FACTORY_YAW:0)+Math.sin(t*.55)*.17}else if(name==='harbor_boat'){const trip=selected&&action>0?Math.sin(Math.min(1,e/12)*Math.PI)*9:0;o.position.set(Math.sin(t*.15)*.85+trip,-.18,3.6+Math.cos(t*.15)*.35+trip*.3);o.rotation.y=trip>0?Math.PI/2:t*.15+Math.PI/2}else if(name==='tree_lift'){if(v2){if(!paused&&!space.reduced)o.position.y=treeLiftY(t)}else o.position.y=-5.3+(Math.sin(t*.16)+1)*4.1}else if(name.startsWith('tree_pod_')){if(v2){if(paused||space.reduced)return;const f=selected?Math.min(1,e/3):(.5+.5*Math.sin(t*.17)),pose=treePodPose(name.endsWith('0')?0:1,f);o.position.set(...pose.position);o.rotation.y=pose.yaw;return}const sign=name.endsWith('0')?-1:1,f=selected?Math.min(1,e/3):(.5+.5*Math.sin(t*.17));o.position.set(sign*(7-f*2),.7,5-f*2);o.rotation.y=sign*-.9}else if(name.startsWith('hub_shuttle_')){const i=Number(name[name.length-1]),a=t*.16+i*2.094,r=HUB_TRACKS[i%2][0];const target=stop?new T.Vector3(...stop.position):null;if(target&&selected){o.position.lerpVectors(new T.Vector3(0,2.4,0),target,Math.min(1,Math.max(0,(e-i*.7)/2.4)));o.position.y+=.6+i*.16}else{o.position.set(Math.sin(a)*r,HUB_TRACKS[i%2][1]+Math.sin(a)*.65+.18,Math.cos(a)*r);o.rotation.y=a+Math.PI/2}}else if(name==='hub_dispatch'){o.rotation.y=selected?Math.sin(Math.min(e,2.4)*.6)*.15:t*.07}else if(name==='campus_ball'){o.position.y=selected==='dut-basketball'?2.15+Math.abs(Math.sin(t*2.5))*.6:2.15}})
 })
 return <group><primitive object={model}/><WorldSigns id={id} refined={v2} v1={revision==='v1'}/>{id==='hyundai'&&<MotorSurfaceLights near={near&&!low} v2={v2}/>}<ProjectPath id={id} stop={stop||null} subtle={v2&&(id==='university'||id==='hyundai')}/>{near&&selected&&<pointLight position={id==='university'?[4.4,-1.2,6]:id==='chongzhen'?[0,2,-1.6]:[0,2,0]} color={id==='opensource'?'#8ae7bb':v2&&id==='university'?'#ffe5c5':'#ffcf8d'} intensity={v2&&id==='university'?1.8:12} distance={v2&&id==='university'?5:8} decay={2}/>}{id==='opensource'&&<Shell/>}{(id==='university'||id==='hyundai')&&<Sign key={id} id={id} v2={v2}/>}
 {stop&&id!=='hyundai'&&<mesh ref={pulse} position={stop.position} rotation={[-Math.PI/2,0,0]}><torusGeometry args={[.7,v2&&id==='university'?.017:.035,6,40]}/><meshBasicMaterial color={id==='chongzhen'?'#ffc77a':v2&&id==='university'?'#6293ad':'#83d9ff'} transparent={v2&&id==='university'} opacity={v2&&id==='university'?.48:1} depthWrite={!(v2&&id==='university')} toneMapped={false}/></mesh>}
 {id==='university'&&<><mesh position={v2?humanPose.position:[-4.4,.15,5.41]} rotation={[0,v2?humanPose.yaw:0,0]}><planeGeometry args={[1.5,2.7]}/><shaderMaterial uniforms={screen} vertexShader={vertex} fragmentShader={`varying vec2 v;uniform float time;uniform float signalOn;void main(){vec2 p=v-.5;float head=1.-smoothstep(.065,.08,length(p-vec2(0.,.29)));float body=(1.-smoothstep(.1,.12,abs(p.x)))*step(-.16,p.y)*step(p.y,.18);float legs=(1.-smoothstep(.027,.04,abs(abs(p.x)-.06)))*step(-.44,p.y)*step(p.y,-.14);float grid=.4+.6*step(.8,fract(v.y*65.-time*.7));gl_FragColor=vec4(vec3(.04,.24,.4)+vec3(.1,.7,1.)*(head+body+legs)*grid*(.4+signalOn*.6),1.);}`}/></mesh>{v2?<CampusMist paused={paused} near={near}/>:<group position={[2.5,0,-5.5]}>{Array.from({length:13},(_,i)=><sprite key={i} position={[Math.sin(i*.7)*4.5,1+(i%4)*1.8,Math.cos(i*.7)*2.5]} scale={[7,6,1]}><shaderMaterial transparent depthWrite={false} vertexShader={`varying vec2 v;void main(){v=uv;vec4 mv=modelViewMatrix*vec4(0.,0.,0.,1.);mv.xy+=position.xy*vec2(length(modelMatrix[0].xyz),length(modelMatrix[1].xyz));gl_Position=projectionMatrix*mv;}`} fragmentShader={`varying vec2 v;void main(){float r=length((v-.5)*2.);float a=pow(max(0.,1.-r*r),2.)*.17;gl_FragColor=vec4(.68,.78,.88,a);}`}/></sprite>)}</group>}</>}
 {id==='hyundai'&&<mesh position={v2?cockpitPoint(musicOverlayLocal):[3.25,7.45,-.909]}><planeGeometry args={v2?[MUSIC_SCREEN.size[0]*COCKPIT_SCALE[0],MUSIC_SCREEN.size[1]*COCKPIT_SCALE[1]]:[2.23,.4]}/><shaderMaterial uniforms={screen} vertexShader={vertex} fragmentShader={`varying vec2 v;uniform float time;void main(){float wave=.5+sin(v.x*18.-time)*.25*sin(v.x*3.14159);float a=exp(-abs(v.y-wave)*40.);gl_FragColor=vec4(vec3(.005,.02,.06)+vec3(.12,.5,1.)*a,1.);}`}/></mesh>}
 </group>
}

export default function DesignedModel(props:Parameters<typeof LegacyModel>[0]&{legacy?:boolean;presentation?:'universe'|'detail';diagnosticStage?:'workbench'|'world-detail'}){return props.id==='bytedance'&&!props.legacy?<HubRefined inUniverse={props.presentation==='universe'} near={props.near} paused={props.paused} selected={props.selected}/>:props.id==='chongzhen'&&!props.legacy?<><HarborRefined near={props.near} paused={props.paused} diagnosticStage={props.presentation==='universe'?'main-space':props.diagnosticStage||'world-detail'}/><WorldSigns id="chongzhen-refined"/></>:<LegacyModel {...props} revision={props.legacy?'original':props.revision||mainWorldRevision(props.id)}/>}
