import {Component,Suspense,useEffect,useRef,useState,type ReactNode} from 'react'
import {Canvas,useFrame,useThree} from '@react-three/fiber'
import {OrbitControls,Html} from '@react-three/drei'
import {EffectComposer,Bloom,SMAA} from '@react-three/postprocessing'
import * as T from 'three'
import {motorRoad} from './builders/motor'
import DesignedModel from './DesignedModel'
import {STOPS,THEMES,type Stop} from './catalog'
import {useSpace} from '../state'
import {pick,workFor,type Lang} from '../data'
import {Project} from '../SpaceHUD'
import './world-explorer.css'
class ModelBoundary extends Component<{children:ReactNode;zh:boolean},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?<Html center><div className="world-load">{this.props.zh?'模型加载失败，请刷新重试。项目仍可从右侧阅读。':'Model could not load. Refresh to retry; stories remain available.'}</div></Html>:this.props.children}}
function Stage({id,selected,action,reset,zoom,rotation,zh}:{id:string;selected:Stop|null;action:number;reset:number;zoom:number;rotation:boolean;zh:boolean}){
 const {camera,size}=useThree(),controls=useRef<any>(null),s=useSpace(),transition=useRef(1),desired=useRef(new T.Vector3(16,12,22)),target=useRef(new T.Vector3()),measure=useRef({elapsed:0,frames:[] as number[]}),follow=useRef<number|null>(null),followElapsed=useRef(9),drivePath=useRef(new T.CatmullRomCurve3(motorRoad.map(q=>new T.Vector3(...q)),true))
 useEffect(()=>{followElapsed.current=action>0&&id==='hyundai'?0:9},[action,id])
 useEffect(()=>{const narrow=size.width<760,scale=narrow?1.45:1.08;desired.current.set(...(selected?.camera||[16,12,22])).multiplyScalar(scale*zoom);target.current.set(...(selected?.position||[0,0,0]));if(selected)desired.current.sub(new T.Vector3(...selected.position).multiplyScalar(.2));transition.current=s.reduced?0:1;if(s.reduced){camera.position.copy(desired.current);controls.current?.target.copy(target.current);controls.current?.update()}},[id,selected,reset,zoom,size.width,camera,s.reduced])
 useFrame((_,dt)=>{if(id==='hyundai'&&followElapsed.current<5&&!s.reduced&&!s.project){followElapsed.current+=dt;follow.current=.05+followElapsed.current*.035;const car=drivePath.current.getPoint(follow.current);camera.position.lerp(car.clone().add(new T.Vector3(7,6,10)),1-Math.exp(-dt*2));controls.current?.target.lerp(car,1-Math.exp(-dt*2));controls.current?.update();transition.current=1}else follow.current=null;if(follow.current===null&&transition.current>0&&!s.project){camera.position.lerp(desired.current,1-Math.exp(-dt*3));controls.current?.target.lerp(target.current,1-Math.exp(-dt*3));controls.current?.update();if(camera.position.distanceTo(desired.current)<.03)transition.current=0}const m=measure.current;m.elapsed+=dt;m.frames.push(dt*1000);if(m.frames.length>300)m.frames.shift();if(m.elapsed>1){m.elapsed=0;const el=document.getElementById('world-performance');if(el){const sorted=[...m.frames].sort((a,b)=>a-b);el.textContent=JSON.stringify({id,width:size.width,height:size.height,frames:m.frames.length,fps:Math.round(1000/(m.frames.reduce((a,b)=>a+b,0)/m.frames.length)),p95ms:Math.round(sorted[Math.floor(sorted.length*.95)]),quality:s.low?'light':'detailed'})}}})
 return <><color attach="background" args={['#0c192a']}/><hemisphereLight args={['#ebf4ff','#978369',.65]}/><directionalLight position={[8,16,15]} color="#fff1d6" intensity={1.8} castShadow shadow-mapSize={[2048,2048]} shadow-camera-left={-14} shadow-camera-right={14} shadow-camera-top={14} shadow-camera-bottom={-14} shadow-normalBias={.04}/><directionalLight position={[-12,7,-8]} color="#acd3ff" intensity={.65}/><ambientLight intensity={.12}/><ModelBoundary zh={zh}><Suspense fallback={<Html center><div className="world-load">{zh?'正在载入这个世界…':'Loading this world…'}</div></Html>}><DesignedModel id={id} selected={selected?.id} action={action} follow={follow} paused={!!s.project} near/></Suspense></ModelBoundary>
 <OrbitControls ref={controls} makeDefault enabled={!s.project} enablePan={false} minDistance={12} maxDistance={65} autoRotate={rotation&&!selected&&!s.reduced&&!s.project} autoRotateSpeed={.2} enableDamping dampingFactor={.12} onStart={()=>{transition.current=0;followElapsed.current=9;follow.current=null}}/>
 {!s.low&&<EffectComposer multisampling={0}><Bloom intensity={.28} luminanceThreshold={1.1} mipmapBlur/><SMAA/></EffectComposer>}
 </>
}
function MusicButton({zh}:{zh:boolean}){const [playing,setPlaying]=useState(false),context=useRef<AudioContext|null>(null);useEffect(()=>()=>{void context.current?.close()},[]);const toggle=()=>{if(playing){void context.current?.close();context.current=null;setPlaying(false);return}const ctx=new AudioContext();context.current=ctx;const gain=ctx.createGain();gain.gain.value=.026;gain.connect(ctx.destination);[196,246.94,293.66].forEach((f,i)=>{const osc=ctx.createOscillator();osc.frequency.value=f;const env=ctx.createGain();env.gain.value=0;env.gain.linearRampToValueAtTime(.2,ctx.currentTime+.7+i*.1);osc.connect(env);env.connect(gain);osc.start()});void ctx.resume();setPlaying(true)};return <button onClick={toggle}>{playing?(zh?'停止氛围音':'Stop sound'):(zh?'试听座舱氛围音':'Try cockpit ambience')}</button>}
export default function WorldExplorer({lang,onLang}:{lang:Lang;onLang:()=>void}){const s=useSpace(),id=s.exploring!,zh=lang==='zh',[selected,setSelected]=useState<Stop|null>(null),[action,setAction]=useState(0),[reset,setReset]=useState(0),[zoom,setZoom]=useState(1),[rotation,setRotation]=useState(false),[fog,setFog]=useState(false),[saved,setSaved]=useState(''),root=useRef<HTMLDivElement>(null)
 useEffect(()=>{root.current?.querySelector<HTMLButtonElement>('button')?.focus();const media=matchMedia('(prefers-reduced-motion: reduce)');if(media.matches)useSpace.getState().update({reduced:true})},[])
 useEffect(()=>{const scope=s.project?root.current?.querySelector('.explorer-project'):root.current;scope?.querySelector<HTMLButtonElement>('button')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();if(useSpace.getState().project)useSpace.getState().openProject(null);else useSpace.getState().update({exploring:null});return}if(e.key==='Tab'){const buttons=Array.from(scope?.querySelectorAll<HTMLElement>('button,a[href]')||[]);if(e.shiftKey&&document.activeElement===buttons[0]){e.preventDefault();buttons[buttons.length-1]?.focus()}else if(!e.shiftKey&&document.activeElement===buttons[buttons.length-1]){e.preventDefault();buttons[0]?.focus()}}};window.addEventListener('keydown',key,true);return()=>window.removeEventListener('keydown',key,true)},[s.project])
 const choose=(stop:Stop)=>{setRotation(false);setSelected(stop);setAction(a=>a+1);setFog(false)}
 return <div ref={root} className="world-explorer" role="dialog" aria-modal="true" aria-label={pick(THEMES[id],lang)}>
 <div className="world-canvas"><Canvas shadows dpr={s.low?1:[1,1.5]} camera={{position:[16,12,22],fov:43,near:.1,far:200}} gl={{antialias:false,preserveDrawingBuffer:import.meta.env.DEV}}><Stage id={id} selected={selected} action={action} reset={reset} zoom={zoom} rotation={rotation} zh={zh}/></Canvas></div>
 <header className="world-top"><button onClick={()=>{s.openProject(null);s.update({exploring:null})}}>↙ {zh?'返回飞行':'Back to flight'}</button><div><small>{zh?'经历世界 / 自由探索':'EXPERIENCE WORLD / EXPLORE'}</small><h1>{pick(THEMES[id],lang)}</h1></div><button onClick={onLang}>{zh?'EN':'中文'}</button></header>
 <aside className="world-story"><p className="world-instruction">{zh?'拖动旋转 · 滚轮或双指缩放':'Drag to rotate · Scroll or pinch to zoom'}</p><nav aria-label={zh?'世界中的故事':'Stories in this world'}>{STOPS[id].map((stop,i)=><button key={stop.id} aria-pressed={selected?.id===stop.id} onClick={()=>choose(stop)}><small>0{i+1}</small>{pick(stop.name,lang)}<span>↗</span></button>)}</nav>
 {id==='university'&&<button className="world-fog" onClick={()=>{setFog(true);setSelected(null);setRotation(false)}}>{zh?'迷雾中的未来经历':'Future stories in the mist'}</button>}
 {fog?<p className="world-description">{zh?'约三分之一的世界留给未来。这里的资料尚待整理，补充后再逐步展开。':'About one third of the world is reserved for the future. These stories will open as details are added.'}</p>:selected?<><h2>{pick(selected.name,lang)}</h2><p className="world-description">{pick(selected.detail,lang)}</p><button className="world-action" onClick={()=>setAction(a=>a+1)}>{pick(selected.action,lang)} ↗</button><button className="world-read" onClick={()=>s.openProject(selected.id)}>{zh?'阅读经历与项目':'Read story & project'} ↗</button>{id==='hyundai'&&<MusicButton zh={zh}/>}</>:<p className="world-description">{zh?'选择一处空间，镜头会带你靠近。你也可以随时拖动，发现另一面。':'Choose a place to move closer, or drag freely to discover the other side.'}</p>}
 </aside>
 {import.meta.env.DEV&&new URLSearchParams(location.search).has('capture')&&<div style={{position:'absolute',top:90,left:28,zIndex:10}}><button onClick={()=>{const canvas=root.current?.querySelector('canvas');canvas?.toBlob(async blob=>{if(!blob)return;const name=`story-${id}-${selected?.id||'overview'}-${Date.now()}.png`;const res=await fetch(`/__qa-artifact?name=${name}`,{method:'POST',body:blob});setSaved(res.ok?'已保存 '+name:'保存失败')})}}>保存模型画面</button><output style={{fontSize:10,display:'block'}}>{saved}</output></div>}
 <footer className="world-controls"><button onClick={()=>{setSelected(null);setFog(false);setZoom(1);setReset(a=>a+1)}}>{zh?'世界全景':'World overview'}</button><button aria-label={zh?'靠近':'Zoom in'} onClick={()=>setZoom(z=>Math.max(.65,z-.15))}>＋</button><button aria-label={zh?'拉远':'Zoom out'} onClick={()=>setZoom(z=>Math.min(1.8,z+.15))}>−</button><button aria-pressed={rotation} onClick={()=>setRotation(!rotation)}>{rotation?(zh?'暂停环绕':'Pause orbit'):(zh?'缓慢环绕':'Slow orbit')}</button><button onClick={()=>{s.openProject(null);s.update({exploring:null,panel:'map'})}}>{zh?'星图':'Atlas'} ↗</button><button onClick={()=>s.update({reduced:!s.reduced})}>{s.reduced?(zh?'减少动态：开':'Reduced motion: on'):(zh?'减少动态：关':'Reduced motion: off')}</button><button onClick={()=>s.update({low:!s.low})}>{s.low?(zh?'轻量画质':'Light quality'):(zh?'精细画质':'Detailed quality')}</button></footer>
 {import.meta.env.DEV&&new URLSearchParams(location.search).has('diagnostics')&&<output id="world-performance"/>}
 {s.project&&<section className="explorer-project" role="dialog" aria-modal="true" aria-label={workFor(s.project,lang).name}><button className="explorer-project-close" onClick={()=>s.openProject(null)}>{zh?'返回世界':'Back to world'} ×</button><Project id={s.project} lang={lang}/><button onClick={()=>s.openProject(null)}>{zh?'返回世界':'Back to world'} ↙</button></section>}
 </div>
}
