import {createRequire} from 'node:module'
import {readFile,writeFile,mkdir,rm} from 'node:fs/promises'
import {resolve,dirname} from 'node:path'
import {fileURLToPath,pathToFileURL} from 'node:url'
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..'),web=resolve(root,'web'),require=createRequire(resolve(web,'package.json')),ts=require('typescript'),temp=resolve(web,'src/universe/worlds/.export')
await mkdir(temp,{recursive:true})
for(const file of ['kit','harbor','tree','hub','landscape','motor']){const source=await readFile(resolve(web,'src/universe/worlds/builders',file+'.ts'),'utf8');const code=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText.replace(/from '(\.\/[^']+)'/g,"from '$1.mjs'");await writeFile(resolve(temp,file+'.mjs'),code)}
globalThis.FileReader=class{readAsArrayBuffer(blob){blob.arrayBuffer().then(result=>{this.result=result;this.onloadend?.()})}}
try{const {GLTFExporter}=await import(pathToFileURL(require.resolve('three/addons/exporters/GLTFExporter.js')));const dest=resolve(web,'public/models/worlds');await mkdir(dest,{recursive:true});const reports=[];for(const [id,file,fn]of [['chongzhen','harbor','buildHarbor'],['opensource','tree','buildTree'],['bytedance','hub','buildHub'],['university','landscape','buildCampus'],['hyundai','motor','buildMotor']]){if(process.argv[2]&&process.argv[2]!==id)continue;const source=await import(pathToFileURL(resolve(temp,file+'.mjs'))),kit=await import(pathToFileURL(resolve(temp,'kit.mjs')));kit.setLightDetail(false);const group=source[fn]();const buffer=await new GLTFExporter().parseAsync(group,{binary:true});await writeFile(resolve(dest,id+'.glb'),Buffer.from(buffer));let meshes=0,triangles=0;group.traverse(o=>{if(o.isMesh){meshes++;triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3}});reports.push({id,bytes:buffer.byteLength,meshes,triangles});console.log(reports.at(-1));kit.setLightDetail(true);const lite=source[fn]();const lowBuffer=await new GLTFExporter().parseAsync(lite,{binary:true});await writeFile(resolve(dest,id+'-low.glb'),Buffer.from(lowBuffer))}const prior=process.argv[2]?JSON.parse(await readFile(resolve(dest,'manifest.json'),'utf8')):[];await writeFile(resolve(dest,'manifest.json'),JSON.stringify([...prior.filter(r=>!reports.some(n=>n.id===r.id)),...reports],null,2))}finally{await rm(temp,{recursive:true,force:true})}
