import {Suspense,useEffect,useRef,useState} from 'react'
import {Canvas,useThree} from '@react-three/fiber'
import {OrbitControls,Html,Environment} from '@react-three/drei'
import {EffectComposer,Bloom,SMAA,N8AO} from '@react-three/postprocessing'
import * as T from 'three'
import DesignedModel from '../universe/worlds/DesignedModel'
import {useSpace} from '../universe/state'
const shots=[
 {id:'overview',name:'整体斜视',camera:[19,14,26],target:[.3,1.3,.6]},
 {id:'front',name:'正面',camera:[0,8.2,28],target:[0,1.3,.4]},
 {id:'side',name:'右侧',camera:[25,10,7],target:[.7,1,0]},
 {id:'back',name:'背面',camera:[16,11,-25],target:[0,1,0]},
 {id:'under',name:'底部',camera:[16,-11,22],target:[0,-.5,0]},
 {id:'meeting',name:'交流室近景',camera:[.3,2.8,5.3],target:[0,1.8,-2.4]},
 {id:'prototype',name:'设计工作间',camera:[-6.2,3.1,7.3],target:[-5.45,1.5,.15]},
 {id:'fabrication',name:'制作工作间',camera:[6.1,3.05,7.6],target:[5.45,1.5,.1]},
 {id:'berth',name:'灵感艇泊位',camera:[13.9,3.8,9],target:[8.65,.52,4.25]},
]
function Stage({index,legacy}:{index:number;legacy:boolean}){const {camera}=useThree(),controls=useRef<any>(null);useEffect(()=>{camera.position.set(...shots[index].camera as [number,number,number]);controls.current?.target.set(...shots[index].target);controls.current?.update()},[camera,index]);return <><color attach="background" args={['#142735']}/><hemisphereLight args={['#e4f1ff','#8f7b65',.9]}/><ambientLight intensity={.12}/><Suspense fallback={null}><Environment files={`${import.meta.env.BASE_URL}textures/env.hdr`} environmentIntensity={.35}/></Suspense><directionalLight position={[-7,13,10]} color="#ffe0b4" intensity={2.65} castShadow shadow-mapSize={[2048,2048]} shadow-camera-left={-14} shadow-camera-right={14} shadow-camera-top={14} shadow-camera-bottom={-14} shadow-normalBias={.025} shadow-bias={-.0001}/><directionalLight position={[11,7,-10]} color="#b7d8f3" intensity={1.1}/><Suspense fallback={<Html center>正在加载模型…</Html>}><DesignedModel id="chongzhen" near paused legacy={legacy}/></Suspense><OrbitControls ref={controls} makeDefault enableDamping dampingFactor={.12} minDistance={2} maxDistance={65}/><EffectComposer multisampling={0}><N8AO aoRadius={.65} intensity={1.1} distanceFalloff={1} quality="medium"/><Bloom intensity={.12} luminanceThreshold={1.4} mipmapBlur/><SMAA/></EffectComposer></>}
export default function HarborReview(){const [index,setIndex]=useState(0),[legacy,setLegacy]=useState(false),[saved,setSaved]=useState(''),[low,setLow]=useState(false),root=useRef<HTMLDivElement>(null);useEffect(()=>{useSpace.getState().update({low,reduced:true,project:null,panel:null})},[low]);return <div className="harbor-review" style={{position:'fixed',inset:0,background:'#142735',color:'#e9ecdf',fontFamily:'system-ui'}}><div ref={root} style={{position:'absolute',inset:'0 0 128px'}}><Canvas shadows dpr={[1,1.5]} camera={{position:[19,14,26],fov:42,near:.05,far:180}} gl={{antialias:false,preserveDrawingBuffer:true,toneMapping:T.ACESFilmicToneMapping}}><Stage index={index} legacy={legacy}/></Canvas></div><div style={{position:'absolute',left:20,right:20,bottom:12,display:'flex',flexWrap:'wrap',gap:8,alignItems:'center'}}><strong style={{width:'100%',fontSize:14}}>崇振建模精调 · 待验收 <span style={{fontWeight:400,color:'#a9bcc7'}}>拖动旋转 · 滚轮缩放 · 右键平移</span></strong>{shots.map((s,i)=><button key={s.id} aria-pressed={index===i} onClick={()=>setIndex(i)}>{s.name}</button>)}<button onClick={()=>setLegacy(v=>!v)}>{legacy?'查看精调版':'对比旧模型'}</button><button onClick={()=>setLow(v=>!v)}>{low?'切换精细模型':'切换轻量模型'}</button><button onClick={()=>{const c=root.current?.querySelector('canvas');c?.toBlob(async b=>{if(!b)return;const name=`harbor-review-${legacy?'before':'after'}-${shots[index].id}.png`;const res=await fetch('/__qa-artifact?name='+name,{method:'POST',body:b});setSaved(res.ok?'已保存 '+name:'保存失败')})}}>保存当前机位</button><a href="/?world=chongzhen" style={{color:'#e8cb9e'}}>常规旋转查看 ↗</a><small style={{width:'100%'}}>{saved||'本轮只做建模与材质，保留原有旋转查看。草图和画作属于场景道具。'}</small></div></div>}
