import {Suspense,useEffect,useRef,useState} from 'react'
import {Canvas,useThree} from '@react-three/fiber'
import {OrbitControls,Html} from '@react-three/drei'
import {EffectComposer,SMAA,Bloom,N8AO} from '@react-three/postprocessing'
import DesignedModel,{LegacyModel} from '../universe/worlds/DesignedModel'
import HarborLighting from '../universe/worlds/HarborLighting'
import HubLighting from '../universe/worlds/HubLighting'
import NaturalWorldLighting from '../universe/worlds/NaturalWorldLighting'
import {stopsForRevision} from '../universe/worlds/modelRevisions'
import {THEMES} from '../universe/worlds/catalog'
import {useSpace} from '../universe/state'
import type {V3} from '../universe/worldConfig'
import FrameProbe,{FrameProbePanel} from './FrameProbe'
import './refinement-review.css'
const worlds=['bytedance','opensource','university','hyundai','chongzhen']
const views:{id:string;name:string;position:V3;target:V3}[]=[{id:'overview',name:'概览',position:[17,12,26],target:[0,0,0]},{id:'front',name:'正面',position:[0,8,30],target:[0,0,0]},{id:'side',name:'侧面',position:[30,7,0],target:[0,0,0]},{id:'back',name:'背面',position:[17,11,-26],target:[0,0,0]},{id:'under',name:'底部',position:[15,-15,25],target:[0,-1,0]}]
function Stage({id,legacy,view,selected,paused,sampleToken}:{id:string;legacy:boolean;view:string;selected:string|null;paused:boolean;sampleToken:number}){
 const controls=useRef<any>(null),{camera}=useThree(),low=useSpace(s=>s.low),reduced=useSpace(s=>s.reduced)
 useEffect(()=>{const stop=stopsForRevision(id,legacy?'original':'v2').find(s=>s.id===selected),shot=views.find(v=>v.id===view)||views[0];camera.position.set(...(stop?.camera||shot.position));controls.current?.target.set(...(stop?.position||shot.target));controls.current?.update()},[id,view,selected,camera,legacy,low])
 return <><color attach="background" args={['#0c192a']}/>{id==='chongzhen'?<HarborLighting/>:id==='bytedance'?<HubLighting/>:!legacy?<NaturalWorldLighting id={id}/>:<><hemisphereLight args={['#ebf4ff','#978369',.65]}/><directionalLight position={[8,16,15]} color="#fff1d6" intensity={1.8} castShadow shadow-mapSize={[2048,2048]} shadow-camera-left={-14} shadow-camera-right={14} shadow-camera-top={14} shadow-camera-bottom={-14} shadow-normalBias={.04}/><directionalLight position={[-12,7,-8]} color="#acd3ff" intensity={.65}/><ambientLight intensity={.12}/></>}
 <Suspense fallback={<Html center>正在加载模型…</Html>}>{id==='chongzhen'?<DesignedModel id={id} near paused={paused} diagnosticStage="workbench"/>:legacy?<LegacyModel id={id} near paused={paused} selected={selected}/>:id==='bytedance'?<DesignedModel id={id} near paused={paused} selected={selected}/>:<LegacyModel id={id} near candidate paused={paused} selected={selected}/>}<FrameProbe stage="refinement-workbench" model={id} revision={legacy?'original':id==='chongzhen'?'v3.2':'v2'} quality={low?'light':'detailed'} view={selected||view} paused={paused} reduced={reduced} sampleToken={sampleToken} outputId="refinement-performance"/></Suspense>
 <OrbitControls ref={controls} makeDefault minDistance={3} maxDistance={70} enableDamping/>{!low&&(id==='chongzhen'?<EffectComposer multisampling={0}><N8AO aoRadius={.65} intensity={1.1} distanceFalloff={1} quality="medium"/><Bloom intensity={.12} luminanceThreshold={1.4} mipmapBlur/><SMAA/></EffectComposer>:<EffectComposer multisampling={0}><Bloom intensity={.28} luminanceThreshold={1.1} mipmapBlur/><SMAA/></EffectComposer>)}</>
}
export default function RefinementReview(){
 const [id,setId]=useState('bytedance'),[legacy,setLegacy]=useState(false),[view,setView]=useState('overview'),[selected,setSelected]=useState<string|null>(null),[paused,setPaused]=useState(false),[status,setStatus]=useState(''),[sampleToken,setSampleToken]=useState(0),low=useSpace(s=>s.low)
 const changeWorld=(world:string)=>{setId(world);setSelected(null);setView('overview');if(world==='chongzhen')setLegacy(false)}
 return <main className="refinement-review"><section className="refinement-stage"><Canvas shadows dpr={1} camera={{position:[17,12,26],fov:43}} gl={{antialias:true,preserveDrawingBuffer:true}}><Stage id={id} legacy={legacy} view={view} selected={selected} paused={paused} sampleToken={sampleToken}/></Canvas></section><aside className="refinement-panel"><a href="/">↙ 返回主页</a><h1>五世界 · 精修工作台</h1><p>本轮五世界造型已获认可；崇振中央艇动态修复已完成网页复检。下一步：主飞船设计。</p><nav>{worlds.map(w=><button key={w} aria-pressed={id===w} onClick={()=>changeWorld(w)}>{THEMES[w][0]}</button>)}</nav><hr/><button disabled={id==='chongzhen'} onClick={()=>setLegacy(v=>!v)}>{legacy?'当前：旧版 · 查看候选':'当前：候选 · 查看旧版'}</button><button onClick={()=>useSpace.getState().update({low:!low})}>{low?'轻量档':'精细档'}</button><button aria-pressed={paused} onClick={()=>setPaused(p=>!p)}>{paused?'当前暂停 · 播放动态':'暂停动态以截图'}</button><small>默认播放；开启减少动态偏好时保持静止。</small><hr/>{views.map(v=><button key={v.id} aria-pressed={view===v.id&&!selected} onClick={()=>{setView(v.id);setSelected(null)}}>{v.name}</button>)}<hr/>{stopsForRevision(id,legacy?'original':'v2').map(s=><button key={s.id} aria-pressed={selected===s.id} onClick={()=>setSelected(s.id)}>{s.name[0]}</button>)}<hr/><button onClick={()=>{document.querySelector('canvas')?.toBlob(async blob=>{if(!blob)return;const name=`refinement-${id}-${legacy?'before':'candidate'}-${selected||view}-${low?'low':'high'}.png`;const res=await fetch(`/__qa-artifact?name=${name}`,{method:'POST',body:blob});setStatus(res.ok?'已保存 '+name:'保存失败')})}}>保存当前网页截图</button><small>{status}</small><p>使用固定概览机位；项目近景与灯光随版本匹配主站。模型仍处开发阶段，文件检查不能代替网页验收。</p><a href="/__refinement-review/">打开进度与证据</a><FrameProbePanel outputId="refinement-performance" resetKey={`${id}:${legacy}:${selected||view}:${paused}:${low}:${sampleToken}`} onResample={()=>setSampleToken(n=>n+1)}/></aside></main>
}
