import * as T from 'three'
import { RoundedBoxGeometry } from 'three/addons/geometries/RoundedBoxGeometry.js'
import { mergeGeometries, mergeVertices } from 'three/addons/utils/BufferGeometryUtils.js'
export let lightDetail=false
export const setLightDetail=(v:boolean)=>{lightDetail=v}
export type V=[number,number,number]
export const v=(p:V)=>new T.Vector3(...p)
export const material=(name:string,color:string,metalness=.05,roughness=.72,emission?:string)=>{const m=new T.MeshStandardMaterial({color,metalness,roughness,emissive:emission||'#000000',emissiveIntensity:emission?.65:0});m.name=name;return m}
export const palette=()=>({ivory:material('ivory','#eee4cc'),white:material('porcelain','#ecf2ef'),stone:material('limestone','#b8a58a'),dark:material('graphite','#233442'),steel:material('steel','#6c8591',.5,.4),wood:material('wood','#bf9670'),green:material('foliage','#457952'),gold:material('ginkgo','#e8ad39'),light:material('warm_lamps','#ffe0a0',0,.6,'#ffbe68'),blue:material('blue_lamps','#76cbff',.1,.4,'#429cff'),water:material('water','#188aab',.28,.28)})
export class Kit{
 root=new T.Group(); static=new T.Group(); boxGeo=new RoundedBoxGeometry(1,1,1,1,.07); plainGeo=new T.BoxGeometry(1,1,1); sphereGeo=new T.IcosahedronGeometry(1,lightDetail?0:1)
 constructor(name:string){this.root.name=name;this.root.add(this.static)}
 mesh(name:string,g:T.BufferGeometry,m:T.Material,p:V=[0,0,0],s:V=[1,1,1],r:V=[0,0,0],parent=this.static){const o=new T.Mesh(g,m);o.name=name;o.position.set(...p);o.scale.set(...s);o.rotation.set(...r);parent.add(o);return o}
 box(name:string,m:T.Material,p:V,s:V,r:V=[0,0,0],parent=this.static,round=true){return this.mesh(name,!lightDetail&&round&&Math.min(...s)>.14?this.boxGeo:this.plainGeo,m,p,s,r,parent)}
 orb(name:string,m:T.Material,p:V,s:V,parent=this.static){return this.mesh(name,this.sphereGeo,m,p,s,[0,0,0],parent)}
 cyl(name:string,m:T.Material,p:V,r:number,h:number,parent=this.static,segments=lightDetail?16:40){return this.mesh(name,new T.CylinderGeometry(r,r,h,segments),m,p,[1,1,1],[0,0,0],parent)}
 tube(name:string,m:T.Material,points:V[],r=.05,parent=this.static,closed=false){const curve=new T.CatmullRomCurve3(points.map(v),closed),segments=lightDetail?Math.max(12,points.length):Math.max(24,points.length*5),sides=lightDetail?4:6,g=new T.TubeGeometry(curve,segments,r,sides,closed);if(/root|branch|braided_trunk/.test(name)){const a=g.attributes.position;for(let i=0;i<=segments;i++){const c=curve.getPointAt(i/segments),f=1-i/segments*.7;for(let j=0;j<=sides;j++){const n=i*(sides+1)+j;a.setXYZ(n,c.x+(a.getX(n)-c.x)*f,c.y+(a.getY(n)-c.y)*f,c.z+(a.getZ(n)-c.z)*f)}}g.computeVertexNormals()}return this.mesh(name,g,m,[0,0,0],[1,1,1],[0,0,0],parent)}
 ring(name:string,m:T.Material,p:V,r:number,t=.035,parent=this.static){return this.mesh(name,new T.TorusGeometry(r,t,lightDetail?4:6,lightDetail?24:64),m,p,[1,1,1],[Math.PI/2,0,0],parent)}
 beam(name:string,m:T.Material,a:V,b:V,r=.05,parent=this.static){const d=v(b).sub(v(a)),o=this.mesh(name,new T.CylinderGeometry(r,r,d.length(),7),m,v(a).addScaledVector(d,.5).toArray() as V,[1,1,1],[0,0,0],parent);o.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),d.normalize());return o}
 tree(p:V,size:number,leaf:T.Material,pal:ReturnType<typeof palette>,seed=0){
 this.beam('trunk',pal.wood,p,[p[0],p[1]+size*1.3,p[2]],size*.045);
 const count=lightDetail?5:14;
 for(let i=0;i<count;i++){const a=i*2.399+seed,h=.45+(i/count)*.85,r=Math.sin(i/count*Math.PI)*size*.34,c:V=[p[0]+Math.sin(a)*r,p[1]+h*size,p[2]+Math.cos(a)*r];if(i%3===0)this.beam('twig',pal.wood,[p[0],p[1]+size*h*.75,p[2]],c,size*.018);this.orb('layered_foliage',leaf,c,[size*.27,size*.16,size*.3])}
 }

 lamp(p:V,pal:ReturnType<typeof palette>,h=.7){this.beam('lamp_post',pal.dark,p,[p[0],p[1]+h,p[2]],.025);this.box('lamp',pal.light,[p[0],p[1]+h,p[2]],[.12,.2,.12])}
 rail(points:V[],pal:ReturnType<typeof palette>,h=.35){this.tube('rail',pal.steel,points.map(p=>[p[0],p[1]+h,p[2]]),.022);for(let i=0;i<points.length;i+=2){const p=points[i];this.beam('post',pal.steel,p,[p[0],p[1]+h,p[2]],.018)}}
 windows(p:V,width:number,height:number,cols:number,rows:number,pal:ReturnType<typeof palette>,parent=this.static){for(let x=0;x<cols;x++)for(let y=0;y<rows;y++){const px=p[0]+(x-(cols-1)/2)*width/cols,py=p[1]+(y-(rows-1)/2)*height/rows;this.box('window_frame',pal.dark,[px,py,p[2]],[width/cols*.7,height/rows*.75,.06],[0,0,0],parent);this.box('warm_window',pal.light,[px,py,p[2]+.035],[width/cols*.52,height/rows*.56,.02],[0,0,0],parent)}}
 desk(p:V,pal:ReturnType<typeof palette>,parent=this.static){this.box('desk',pal.wood,[p[0],p[1]+.42,p[2]],[.85,.09,.45],[0,0,0],parent);for(const x of [-.32,.32])this.box('desk_leg',pal.dark,[p[0]+x,p[1]+.2,p[2]],[.035,.4,.3],[0,0,0],parent);this.box('monitor',pal.dark,[p[0],p[1]+.66,p[2]],[.42,.3,.05],[0,0,0],parent);this.box('monitor_screen',pal.blue,[p[0],p[1]+.66,p[2]+.03],[.35,.22,.01],[0,0,0],parent);this.box('chair',pal.dark,[p[0],p[1]+.25,p[2]+.55],[.35,.08,.35],[0,0,0],parent);this.box('chair_back',pal.dark,[p[0],p[1]+.48,p[2]+.72],[.35,.4,.055],[.1,0,0],parent);this.beam('chair_stem',pal.steel,[p[0],p[1],p[2]+.55],[p[0],p[1]+.23,p[2]+.55],.025,parent)}
 car(name:string,m:T.Material,pal:ReturnType<typeof palette>,p:V=[0,0,0],scale=1){const g=new T.Group();g.name=name;g.position.set(...p);g.scale.setScalar(scale);this.root.add(g);this.box('body',m,[0,.22,0],[.55,.25,1.05],[0,0,0],g);this.box('cabin',pal.dark,[0,.4,-.04],[.45,.24,.58],[0,0,0],g);this.box('roof',m,[0,.53,-.04],[.4,.035,.4],[0,0,0],g);for(const x of [-.25,.25])for(const z of [-.3,.3]){this.mesh('tire',new T.CylinderGeometry(.135,.135,.09,lightDetail?8:16),pal.dark,[x,.15,z],[1,1,1],[0,0,Math.PI/2],g);this.mesh('wheel_hub',new T.CylinderGeometry(.075,.075,.095,12),pal.steel,[x,.15,z],[1,1,1],[0,0,Math.PI/2],g)}for(const x of [-.18,.18])this.box('headlamp',pal.light,[x,.26,.53],[.13,.055,.02],[0,0,0],g);return g}
 finish(){this.static.updateMatrixWorld(true);const buckets=new Map<T.Material,T.BufferGeometry[]>();this.static.traverse(o=>{if(o instanceof T.Mesh){let g=o.geometry.clone().applyMatrix4(o.matrixWorld);if(g.index)g=g.toNonIndexed();g.deleteAttribute('uv');const key=o.material as T.Material;const gs=buckets.get(key)||[];gs.push(g);buckets.set(key,gs)}});this.static.clear();for(const [m,gs]of buckets){const g=mergeGeometries(gs);if(g){const indexed=mergeVertices(g);g.dispose();const o=new T.Mesh(indexed,m);o.name=m.name;this.static.add(o)}gs.forEach(g=>g.dispose())}return this.root}
}
export function road(k:Kit,name:string,points:V[],width:number,pal:ReturnType<typeof palette>,closed=true){const c=new T.CatmullRomCurve3(points.map(v),closed),n=180,vertices:number[]=[],normals:number[]=[],idx:number[]=[];for(let i=0;i<=n;i++){const t=i/n,p=c.getPoint(t),d=c.getTangent(t),side=new T.Vector3(-d.z,0,d.x).normalize();for(const s of [-1,1]){const q=p.clone().addScaledVector(side,width*s/2);vertices.push(...q.toArray());normals.push(0,1,0)}if(i<n){const j=i*2;idx.push(j,j+2,j+1,j+1,j+2,j+3)}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(vertices,3));g.setAttribute('normal',new T.Float32BufferAttribute(normals,3));g.setIndex(idx);k.mesh(name,g,pal.dark);for(const s of [-1,1]){const edge=Array.from({length:91},(_,i)=>{const t=i/90,p=c.getPoint(t),d=c.getTangent(t);return p.addScaledVector(new T.Vector3(-d.z,0,d.x).normalize(),width*s*.5).add(new T.Vector3(0,.03,0)).toArray() as V});k.tube(name+'_curb',pal.ivory,edge,.045)}for(let i=0;i<60;i++){const t=i/60,p=c.getPoint(t),d=c.getTangent(t);k.box('road_dash',pal.ivory,[p.x,p.y+.024,p.z],[.035,.015,.24],[0,Math.atan2(d.x,d.z),0])}return c}
