import {createRequire} from 'node:module'
import {pathToFileURL} from 'node:url'
const require=createRequire(new URL('../../web/package.json',import.meta.url))
export const T=await import(pathToFileURL(require.resolve('three')))
const {RoundedBoxGeometry}=await import(pathToFileURL(require.resolve('three/addons/geometries/RoundedBoxGeometry.js')))
const {mergeGeometries,mergeVertices}=await import(pathToFileURL(require.resolve('three/addons/utils/BufferGeometryUtils.js')))
export const vec=p=>new T.Vector3(...p)
export function mat(name,color,roughness=.65,metalness=0,emissive){const m=new T.MeshStandardMaterial({color,roughness,metalness,emissive:emissive||0,emissiveIntensity:emissive?.45:1});m.name=name;return m}
export class Workshop {
 constructor(name,low=false){this.low=low;this.root=new T.Group();this.root.name=name;this.fixed=new T.Group();this.fixed.name='architecture';this.root.add(this.fixed);this.parent=this.fixed;this.parts=[];this.inventory=[]}
 mesh(name,g,m,p=[0,0,0],r=[0,0,0]){const o=new T.Mesh(g,m);o.name=name;o.position.set(...p);o.rotation.set(...r);o.castShadow=!m.transparent;o.receiveShadow=true;this.parent.add(o);this.inventory.push(name);return o}
 uv(g){const p=g.attributes.position,n=g.attributes.normal,a=[];for(let i=0;i<p.count;i++){const axis=[Math.abs(n.getX(i)),Math.abs(n.getY(i)),Math.abs(n.getZ(i))];const j=axis.indexOf(Math.max(...axis));a.push(j===0?p.getZ(i):p.getX(i),j===1?p.getZ(i):p.getY(i))}g.setAttribute('uv',new T.Float32BufferAttribute(a,2));return g}
 box(name,m,p,s,r=[0,0,0],bevel=.025){const b=Math.min(bevel,Math.min(...s)*.18);return this.mesh(name,this.uv(b>0&&!this.low&&Math.min(...s)>.045?new RoundedBoxGeometry(...s,1,b):new T.BoxGeometry(...s)),m,p,r)}
 cyl(name,m,p,rt,rb,h,r=[0,0,0],seg=this.low?16:40){return this.mesh(name,new T.CylinderGeometry(rt,rb,h,seg),m,p,r)}
 beam(name,m,a,b,r=.035){const d=vec(b).sub(vec(a)),o=this.cyl(name,m,vec(a).addScaledVector(d,.5).toArray(),r,r,d.length(),undefined,this.low?6:12);o.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),d.normalize());return o}
 sphere(name,m,p,s){const o=this.mesh(name,new T.SphereGeometry(1,this.low?8:16,this.low?6:12),m,p);o.scale.set(...s);return o}
 tube(name,m,points,r=.03,closed=false){return this.mesh(name,new T.TubeGeometry(new T.CatmullRomCurve3(points.map(vec),closed),this.low?32:96,r,this.low?6:10,closed),m)}
 ring(name,m,p,r,thick=.025,rotation=[Math.PI/2,0,0]){return this.mesh(name,new T.TorusGeometry(r,thick,this.low?6:10,this.low?36:96),m,p,rotation)}
 group(name,p,fn,rotation=[0,0,0],moving=false){const prev=this.parent,g=new T.Group();g.name=name;g.position.set(...p);g.rotation.set(...rotation);(moving?this.root:this.parent).add(g);this.parent=g;fn();this.parent=prev;if(moving)this.parts.push(g);return g}
 // Closed thick circular wall/slab with planar UVs; no overlapped transparent concentric shells.
 arc(name,m,p,inner,outer,height,start=0,length=Math.PI*2){const s=new T.Shape();s.absarc(0,0,outer,start,start+length,false);s.lineTo(Math.cos(start+length)*inner,Math.sin(start+length)*inner);s.absarc(0,0,inner,start+length,start,true);s.closePath();const g=new T.ExtrudeGeometry(s,{depth:height,bevelEnabled:false,curveSegments:Math.max(2,Math.ceil(length*outer*(this.low?1.1:2.2)))});// Smooth only the curved vertical faces. Preserve hard cap and radial-end normals.
 const positions=g.attributes.position,normals=g.attributes.normal;for(let i=0;i<positions.count;i++){if(Math.abs(normals.getZ(i))>.1)continue;const x=positions.getX(i),y=positions.getY(i),radius=Math.hypot(x,y);if(radius<1e-6)continue;const dot=(normals.getX(i)*x+normals.getY(i)*y)/radius;if(Math.abs(dot)>.8){const sign=dot<0?-1:1;normals.setXYZ(i,sign*x/radius,sign*y/radius,0)}}
 return this.mesh(name,this.uv(g),m,p,[-Math.PI/2,0,0])}
 // Rectangular, closed, capped sweep: useful for beams/roadbeds, unlike round prototype pipes.
 ribbon(name,m,points,width,depth,closed=false){const curve=new T.CatmullRomCurve3(points.map(vec),closed),n=this.low?96:240,positions=[],uv=[],index=[];for(let i=0;i<=n;i++){const t=i/n,p=curve.getPoint(t),d=curve.getTangent(t),side=new T.Vector3(d.z,0,-d.x).normalize();for(const [w,h]of [[-1,0],[1,0],[1,-depth],[-1,-depth]]){positions.push(p.x+side.x*w*width/2,p.y+h,p.z+side.z*w*width/2);uv.push(w*.5+.5,t*curve.getLength())}}for(let i=0;i<n;i++)for(let j=0;j<4;j++){const a=i*4+j,b=i*4+(j+1)%4,c=a+4,d=b+4;index.push(a,c,b,b,c,d)}if(!closed)index.push(0,1,2,0,2,3,n*4,n*4+2,n*4+1,n*4,n*4+3,n*4+2);const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(index);g.computeVertexNormals();return this.mesh(name,g,m)}
 finish(){this.root.updateMatrixWorld(true);if(this.audit)return this.root;const mergeGroup=group=>{const buckets=new Map(),inv=new T.Matrix4().copy(group.matrixWorld).invert();group.traverse(o=>{if(!o.isMesh)return;const g=o.geometry.clone().applyMatrix4(new T.Matrix4().multiplyMatrices(inv,o.matrixWorld));if(g.index){const expanded=g.toNonIndexed();g.dispose();if(!buckets.has(o.material))buckets.set(o.material,[]);buckets.get(o.material).push(expanded)}else{if(!buckets.has(o.material))buckets.set(o.material,[]);buckets.get(o.material).push(g)}});const old=[];group.traverse(o=>{if(o.isMesh)old.push(o.geometry)});group.clear();for(const [m,gs]of buckets){const merged=mergeGeometries(gs,false);if(!merged)throw Error('Attribute mismatch '+m.name);const welded=mergeVertices(merged,1e-5),o=new T.Mesh(welded,m);o.name=m.name;o.castShadow=!m.transparent;o.receiveShadow=true;group.add(o);merged.dispose();gs.forEach(g=>g.dispose())}old.forEach(g=>g.dispose())};mergeGroup(this.fixed);this.parts.forEach(mergeGroup);this.root.userData={...this.root.userData,source:'blender/five-worlds',quality:this.low?'light':'detailed',inventory:this.inventory};return this.root}
}
