// CPU silhouette / construction review only. This does NOT reproduce the browser renderer.
import {resolve} from 'node:path'
import {mkdir} from 'node:fs/promises'
import {writeFile,readFile} from 'node:fs/promises'
import {createRequire} from 'node:module'
import {pathToFileURL} from 'node:url'
import {T} from './geometry.mjs'
const require=createRequire(new URL('../../交付物/package.json',import.meta.url)),{NodeIO}=await import(pathToFileURL(require.resolve('@gltf-transform/core'))),{ALL_EXTENSIONS}=await import(pathToFileURL(require.resolve('@gltf-transform/extensions')))
const arg=name=>{const i=process.argv.indexOf(name);return i<0?null:process.argv[i+1]};
const version=process.argv.includes('--v2')?'v2':'v1';
const world=process.argv[2]||'bytedance',side=process.argv[3]||'overview',detailed=process.argv.includes('--detailed'),file=new URL(`../../web/public/models/worlds/${world}-refined-${version}${detailed?'':'-low'}.glb`,import.meta.url),doc=await new NodeIO().registerExtensions(ALL_EXTENSIONS).read(arg('--asset')||file.pathname),W=1000,H=900,zbuf=new Float32Array(W*H).fill(Infinity),rgba=new Uint8Array(W*H*4)
for(let i=0;i<W*H;i++)rgba.set([20,31,45,255],i*4)
const webRequire=createRequire(new URL('../../web/package.json',import.meta.url)),ts=webRequire('typescript'),code=ts.transpileModule(await readFile(new URL('../../web/src/universe/worlds/catalog.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText,{STOPS}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64')),stop=side.startsWith('story-')?STOPS[world][Number(side.slice(6))-1]:null;
const camera=new T.PerspectiveCamera(43,W/H,.1,200);camera.position.set(...(stop?stop.camera:side==='back'?[17,11,-26]:side==='under'?[15,-15,25]:side==='front'?[0,8,30]:side==='side'?[30,7,0]:[17,12,26]));camera.lookAt(...(stop?.position||[0,0,0]));if(arg('--camera'))camera.position.set(...JSON.parse(arg('--camera')));const target=arg('--target')?JSON.parse(arg('--target')):stop?.position||[0,0,0];camera.lookAt(...target);camera.updateMatrixWorld();const vp=new T.Matrix4().multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse),light=new T.Vector3(8,16,15).normalize(),fill=new T.Vector3(-12,7,-8).normalize();const draw=[]
for(const node of doc.getRoot().listNodes()){const mesh=node.getMesh();if(!mesh)continue;const matrix=new T.Matrix4().fromArray(node.getWorldMatrix()),normal=new T.Matrix3().getNormalMatrix(matrix);for(const prim of mesh.listPrimitives()){const mat=prim.getMaterial(),alpha=mat?.getBaseColorFactor()?.[3]??1;if(alpha<.3)continue;const color=mat?.getBaseColorFactor()||[.8,.8,.8,1],emissive=mat?.getEmissiveFactor()||[0,0,0],pa=prim.getAttribute('POSITION'),na=prim.getAttribute('NORMAL'),ca=prim.getAttribute('COLOR_0'),ia=prim.getIndices(),points=[],shades=[],p=[],n=[],c=[];for(let i=0;i<pa.getCount();i++){pa.getElement(i,p);na.getElement(i,n);const point=new T.Vector3(...p).applyMatrix4(matrix).applyMatrix4(vp),norm=new T.Vector3(...n).applyMatrix3(normal).normalize(),s=.36+.75*Math.max(0,norm.dot(light))+.2*Math.max(0,norm.dot(fill));if(ca)ca.getElement(i,c);else c.splice(0,4,1,1,1,1);points.push([(point.x*.5+.5)*W,(-point.y*.5+.5)*H,point.z]);shades.push(color.slice(0,3).map((v,k)=>Math.round(255*Math.min(1,Math.max(0,v*(c[k]??1)*s+emissive[k]*.18))**(1/2.2))))}const count=ia?.getCount()||pa.getCount();for(let i=0;i<count;i+=3){const ids=[0,1,2].map(j=>ia?ia.getScalar(i+j):i+j),v=ids.map(j=>points[j]);if(v.some(p=>p[2]<-1||p[2]>1))continue;const [a,b,c]=v,area=(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);if(Math.abs(area)<.0001)continue;draw.push({v,area,color:ids.map(j=>shades[j])})}}}
for(const {v:[a,b,c],area,color}of draw){const x0=Math.max(0,Math.floor(Math.min(a[0],b[0],c[0]))),x1=Math.min(W-1,Math.ceil(Math.max(a[0],b[0],c[0]))),y0=Math.max(0,Math.floor(Math.min(a[1],b[1],c[1]))),y1=Math.min(H-1,Math.ceil(Math.max(a[1],b[1],c[1])));for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){const u=((b[0]-x)*(c[1]-y)-(b[1]-y)*(c[0]-x))/area,w=((c[0]-x)*(a[1]-y)-(c[1]-y)*(a[0]-x))/area,t=1-u-w;if(u<0||w<0||t<0)continue;const z=a[2]*u+b[2]*w+c[2]*t,idx=y*W+x;if(z>=zbuf[idx])continue;zbuf[idx]=z;for(let j=0;j<3;j++)rgba[idx*4+j]=color[0][j]*u+color[1][j]*w+color[2][j]*t}}
const dest=new URL(`../../交付物/五世界精修总计划-20260924/实施记录-20260926/${world}-${side}-${version}-cpu.rgba`,import.meta.url);const outputAt=process.argv.indexOf('--output-dir'),output=outputAt<0?dest:resolve(process.argv[outputAt+1],`${world}-${side}-${version}-${detailed?'high':'low'}-cpu.rgba`);if(outputAt>=0)await mkdir(resolve(process.argv[outputAt+1]),{recursive:true});await writeFile(output,rgba);console.log(JSON.stringify({world,side,width:W,height:H,path:outputAt<0?dest.pathname:output,quality:detailed?'detailed':'light',camera:camera.position.toArray(),target,triangles:draw.length,note:'CPU structural preview, not browser evidence; omits transparency, texture and shadows'}))
