import { CAMPUS_STORIES } from './worlds/campusStories'
import { useEffect, useRef, useState, type ReactNode } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { WORLDS, projectWorld, worldFor, periodFor, RACE, SHARDS, pick, workFor, type Lang } from './data'
import { clearInput, flightInput as input, useSpace } from './state'
import StarAtlas from './StarAtlas'
import { positionOf } from './worldMotion'
import ExperiencePanel from './ExperiencePanel'
import { getWorkDoc } from '../data/workDocs'

function Modal({children,label,onClose,atlas=false}:{children:ReactNode;label:string;onClose:()=>void;atlas?:boolean}){
 const ref=useRef<HTMLElement>(null)
 useEffect(()=>{ref.current?.scrollTo({top:0});ref.current?.querySelector<HTMLButtonElement>('button')?.focus()},[label])
 useEffect(()=>{clearInput();const prev=document.activeElement as HTMLElement;const root=ref.current;root?.querySelector<HTMLButtonElement>('button')?.focus();const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab'||!root)return;const all=Array.from(root.querySelectorAll<HTMLElement>('button:not(:disabled), a[href], input'));if(e.shiftKey&&document.activeElement===all[0]){e.preventDefault();all[all.length - 1]?.focus()}else if(!e.shiftKey&&document.activeElement===all[all.length - 1]){e.preventDefault();all[0]?.focus()}};document.addEventListener('keydown',trap);return()=>{document.removeEventListener('keydown',trap);prev?.focus()}},[])
 return <div className="space-modal-backdrop" onClick={onClose}><section ref={ref} className={`space-modal ${atlas?'atlas-modal':''}`} role="dialog" aria-modal="true" aria-label={label} onClick={e=>e.stopPropagation()}><button className="space-modal-close" aria-label={label==='Star chart'?'Close':'关闭 / Close'} onClick={onClose}>×</button>{children}</section></div>
}
export function Project({id,lang}:{id:string;lang:Lang}){
 const item=workFor(id,lang),doc=CAMPUS_STORIES[id]?{year:undefined,role:undefined,tags:undefined,link:undefined,body:pick(CAMPUS_STORIES[id].body,lang)}:getWorkDoc(id,lang),planet=projectWorld(id),zh=lang==='zh'
 return <><p className="space-eyebrow">{planet?pick(planet.name,lang):''} / {id==='ai-music-wallpaper'?(zh?'主星球 / 智能座舱':'MAIN WORLD / SMART COCKPIT'):(zh?'经历项目':'EXPERIENCE PROJECT')}</p><h2>{item.name}</h2>{id==='ai-music-wallpaper'&&<p className="space-modal-lead">{zh?'现代汽车经历位于这颗海岸微缩世界，AI 音乐壁纸对应上部音乐座舱。上半部工厂仅为视觉主题，不代表制造相关工作经历。':'This blue-and-white world represents the Hyundai internship. AI Music Wallpaper lives in its upper music cockpit. The factory is a visual theme, not a claim of manufacturing experience.'}</p>}<p className="space-modal-lead">{doc?.role||item.meta}</p>{doc?<><div className="space-project-meta"><span>{doc.year}</span>{doc.tags?.map(t=><span key={t}>{t}</span>)}</div>{id==='material-gen-agent'&&<figure className="method-flow"><figcaption>{zh?'方法示意 · 四个可复用的 Skill':'METHOD DIAGRAM · FOUR REUSABLE SKILLS'}</figcaption><ol>{(zh?['素材处理','案例叙事','模板回填','质量校验']:['Source material','Case narrative','Template filling','Quality checks']).map((step,i)=><li key={step}><small>0{i+1}</small>{step}</li>)}</ol><p>{zh?'语义判断交给模型，格式与来源校验交给确定性代码。':'Model judgment for meaning; deterministic code for format and source validation.'}</p></figure>}<div className="space-project-body"><ReactMarkdown remarkPlugins={[remarkGfm]}>{doc.body}</ReactMarkdown></div>{(doc.link||item.link)&&<a className="space-project-link" href={doc.link||item.link} target="_blank" rel="noopener noreferrer">{zh?'访问项目':'Visit project'} ↗</a>}</>:<div className="pending-project"><span>✧</span><h3>{zh?'这一颗星，还在书写。':'This star is still being written.'}</h3><p>{zh?'这段经历的项目资料尚待补充，不代表新增项目或成果。':'Project details for this experience are still to be added. No additional achievement is claimed.'}</p></div>}</>
}
function Help({lang}:{lang:Lang}){
 const zh=lang==='zh'
 return <><p className="space-eyebrow">{zh?'飞行指南':'FLIGHT MANUAL'}</p><h2>{zh?'慢慢飞，去发现。':'Take your time. Find your orbit.'}</h2><p className="space-modal-lead">{zh?'五颗主星球，五段经历。接近星球打开项目列表，再阅读其中的故事；星图也可以直接领航或阅读。':'Five worlds, five chapters. Approach a world to choose its projects, or use the atlas to navigate and read directly.'}</p><div className="flight-manual">{[['W A S D / ↑ ↓ ← →',zh?'前进、后退与转向':'Forward, reverse & turn'],['Q / E',zh?'下降 / 上升':'Descend / ascend'],['Shift',zh?'加速飞行':'Boost'],[zh?'空格':'Space',zh?'制动':'Brake'],['F',zh?'打开附近经历':'Open nearby experience'],['M',zh?'星图与自动领航':'Star chart & guided flight'],['R',zh?'返回起点':'Return to origin'],['Esc',zh?'关闭面板 / 暂停':'Close panel / pause'],[zh?'鼠标拖动':'Drag',zh?'环顾飞船四周':'Look around your vessel']].map(([a,b])=><div key={a}><kbd>{a}</kbd><span>{b}</span></div>)}</div><p className="space-modal-lead">{zh?'手机：左侧摇杆飞行，右侧按钮升降、加速和制动。星图可自动领航。项目内容不需要完成挑战即可阅读。':'On mobile: fly with the left stick; use right buttons to climb, descend, boost and brake. Use the chart for guided flight. Stories are always available without completing challenges.'}</p></>
}
function TouchControls({lang}:{lang:Lang}){
 const stick=useRef<HTMLDivElement>(null),[knob,setKnob]=useState([0,0])
 const update=(e:React.PointerEvent)=>{if(!e.currentTarget.hasPointerCapture(e.pointerId))return;const r=e.currentTarget.getBoundingClientRect();let x=(e.clientX-r.left-r.width/2)/42,y=(e.clientY-r.top-r.height/2)/42;const n=Math.max(1,Math.hypot(x,y));x/=n;y/=n;input.turn=x;input.thrust=-y;setKnob([x*30,y*30])}
 const held=(key:'lift'|'boost'|'brake',value:number|boolean)=>({onPointerDown:(e:React.PointerEvent<HTMLButtonElement>)=>{e.currentTarget.setPointerCapture(e.pointerId);if(key==='lift')input.lift=value as number;else input[key]=value as boolean},onPointerUp:()=>{if(key==='lift')input.lift=0;else input[key]=false},onPointerCancel:()=>{if(key==='lift')input.lift=0;else input[key]=false},onLostPointerCapture:()=>{if(key==='lift')input.lift=0;else input[key]=false}})
 return <div className="touch-controls"><div ref={stick} className="flight-stick" role="group" aria-label={lang==='zh'?'飞行摇杆':'Flight stick'} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);update(e)}} onPointerMove={update} onPointerUp={()=>{input.turn=0;input.thrust=0;setKnob([0,0])}} onPointerCancel={()=>{input.turn=0;input.thrust=0;setKnob([0,0])}} onLostPointerCapture={()=>{input.turn=0;input.thrust=0;setKnob([0,0])}}><i style={{transform:`translate(${knob[0]}px,${knob[1]}px)`}}/></div><div className="touch-actions"><button {...held('lift',1)} aria-label={lang==='zh'?'上升':'Ascend'}>↑</button><button {...held('boost',true)}>{lang==='zh'?'加速':'Boost'}</button><button {...held('lift',-1)} aria-label={lang==='zh'?'下降':'Descend'}>↓</button><button {...held('brake',true)}>{lang==='zh'?'制动':'Brake'}</button></div></div>
}
function AudioBed(){
 const sound=useSpace(s=>s.sound)
 useEffect(()=>{if(!sound)return;let ctx:AudioContext;try{ctx=new AudioContext()}catch{return}const gain=ctx.createGain();gain.gain.value=.022;gain.connect(ctx.destination);const oscillators=[55,82.41,110].map((frequency,i)=>{const osc=ctx.createOscillator();osc.type='sine';osc.frequency.value=frequency;const g=ctx.createGain();g.gain.value=i===0?.7:.15;osc.connect(g);g.connect(gain);osc.start();return osc});void ctx.resume();const timer=setInterval(()=>{gain.gain.setTargetAtTime(document.hidden?0:.018+useSpace.getState().speed*.0005,ctx.currentTime,.3)},250);return()=>{clearInterval(timer);oscillators.forEach(o=>o.stop());void ctx.close()}},[sound])
 return null
}
export default function SpaceHUD({lang,onLang,onExit,ready}:{lang:Lang;onLang:()=>void;onExit:()=>void;ready:boolean}){
 const s=useSpace(),zh=lang==='zh',exitRef=useRef(onExit),[confirmReset,setConfirmReset]=useState(false)
 exitRef.current=onExit
 const nearest=s.nearest?worldFor(s.nearest):null
 const current=WORLDS.find(g=>Math.hypot(...positionOf(g).map((v,i)=>v-s.position[i]))<g.radius+70)
 const next=WORLDS.find(g=>g.id===s.destination)
 const checkpointPosition=RACE[Math.min(s.checkpoint,RACE.length-1)]
 const ringBearing=Math.atan2(-(checkpointPosition[0]-s.position[0]),-(checkpointPosition[2]-s.position[2]))-s.heading
 useEffect(()=>{if(!ready)return;const keydown=(e:KeyboardEvent)=>{const state=useSpace.getState();if(e.code==='Escape'){e.preventDefault();if(state.exploring){if(state.project)state.openProject(null);else state.update({exploring:null});return}if(state.project)state.openProject(null);else state.setPanel(state.panel?null:'settings');return}if(e.code==='KeyM'&&!state.project&&!e.repeat){e.preventDefault();state.setPanel(state.panel==='map'?null:'map');return}if(e.repeat||state.project||state.panel||state.exploring)return;if(e.target instanceof HTMLElement&&['INPUT','TEXTAREA'].includes(e.target.tagName))return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();input.keys.add(e.code);if(e.code==='KeyM')state.setPanel('map');if(e.code==='KeyF'&&state.nearest)state.openExperience(state.nearest);if(e.code==='KeyR'){state.update({resetFlight:state.resetFlight+1,destination:null,race:false,checkpoint:0,raceTime:0,notice:'reset'})}};const up=(e:KeyboardEvent)=>input.keys.delete(e.code);const blur=()=>clearInput();const visibility=()=>{clearInput();if(document.hidden)useSpace.getState().setPanel('settings')};let dragging=false,lastX=0,lastY=0;const down=(e:PointerEvent)=>{if((e.target as HTMLElement).tagName!=='CANVAS'||e.pointerType==='touch')return;dragging=true;lastX=e.clientX;lastY=e.clientY};const move=(e:PointerEvent)=>{if(!dragging)return;input.lookX=THREEClamp(input.lookX+(lastX-e.clientX)*.006,-1.5,1.5);input.lookY=THREEClamp(input.lookY+(e.clientY-lastY)*.035,-2,9);lastX=e.clientX;lastY=e.clientY};const end=()=>{dragging=false;input.lookX=0;input.lookY=0};window.addEventListener('keydown',keydown);window.addEventListener('keyup',up);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility);window.addEventListener('pointerdown',down);window.addEventListener('pointermove',move);window.addEventListener('pointerup',end);return()=>{clearInput();window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('pointerdown',down);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end)}},[ready])
 useEffect(()=>{if(!s.notice)return;const t=setTimeout(()=>useSpace.getState().update({notice:null}),3500);return()=>clearTimeout(t)},[s.notice])
 const notice=s.notice==='shard'?(zh?'拾获星尘 · 星图已更新':'Stardust collected · Chart updated'):s.notice==='secret'?(zh?'发现隐秘回声 · 好奇心自有回响':'Hidden echo found · Curiosity resonates'):s.notice==='finish'?(zh?'航线完成 · 成绩已保存在本机':'Course complete · Time saved on this device'):s.notice==='race'?(zh?'穿过前方的发光星环，开始挑战':'Fly through the illuminated rings'):s.notice==='boundary'?(zh?'已抵达星图边缘 · 请调头返航':'Chart boundary · Turn back toward the stars'):s.notice==='reset'?(zh?'已返回起点':'Returned to origin'):s.notice?.startsWith('visit:')?(zh?'发现经历 · ':'World discovered · ')+pick(WORLDS.find(g=>g.id===s.notice?.split(':')[1])!.name,lang):''
 return <div className={`space-hud ${ready?'is-ready':''}`}>
 <AudioBed/>
 <header className="space-topbar"><button className="space-home" aria-label={zh?'返回肖像':'Back to portrait'} onClick={onExit}>↙ <span>{zh?'返回肖像':'Back to portrait'}</span></button><div className="space-brand"><strong>{zh?'航驰星野':'SPIKE / STARFIELD'}</strong><span>{zh?'经历在此相遇':'A UNIVERSE OF EXPERIENCES'}</span></div><div className="space-top-actions"><button onClick={onLang} aria-label="切换语言 / Switch language">{zh?'EN':'中文'}</button><button onClick={()=>s.setPanel('settings')} aria-label={zh?'设置':'Settings'}>⋯</button></div></header>
 <aside className="space-location"><p className="space-eyebrow">{zh?'当前坐标':'CURRENT SECTOR'}</p><h1>{current?pick(current.name,lang):zh?'星际之间':'Between the stars'}</h1><p>{current?pick(current.role,lang):zh?'沿着好奇心，寻找下一颗星。':'Follow your curiosity to the next star.'}</p>{current&&<p>{periodFor(current,lang)}</p>}{current&&<p className="sector-description">{pick(current.description,lang)}</p>}{!current&&!next&&<button className="suggested-destination" onClick={()=>s.navigate('bytedance')}>{zh?'向字节跳动启航':'Set course for ByteDance'} ↗</button>}{next&&<div className="autopilot"><i/>{zh?'正在领航至':'Navigating to'} {pick(next.name,lang)}<button onClick={()=>s.navigate(null)}>{zh?'接管':'Take over'}</button></div>}</aside>
 <nav className="space-nav" aria-label={zh?'探索工具':'Explorer tools'}><button onClick={()=>s.setPanel('map')}><span>✧</span>{zh?'星图':'Star chart'} <kbd>M</kbd></button><button onClick={()=>s.setPanel('help')}><span>?</span>{zh?'飞行指南':'Flight guide'}</button></nav>
 <div className="flight-reticle" aria-hidden="true"><i/><i/></div>
 {nearest&&s.distance<45&&!s.panel&&!s.project&&!s.race&&<button className="proximity-card" onClick={()=>s.openExperience(s.nearest!)}><span>{s.nearest==='hyundai'?(zh?'现代汽车 · 智能座舱':'HYUNDAI · SMART COCKPIT'):(zh?'附近的经历星球':'NEARBY EXPERIENCE')}</span><strong>{pick(nearest.name,lang)}</strong><small>{zh?'打开经历':'Explore world'} <kbd className="desktop-key">F</kbd> · {s.distance} {zh?'距离单位':'units'}</small></button>}
 <footer className="flight-telemetry"><div className="speed-meter"><strong>{String(s.speed).padStart(2,'0')}</strong><span>{zh?'航速':'SPEED'}<small>{zh?'模拟单位 / 秒':'SIM UNITS / S'}</small></span><i style={{height:Math.max(5,s.speed/49*38)}}/></div><div className="flight-hint">{zh?'WASD 飞行 · Q / E 升降 · Shift 加速':'WASD move · Q / E altitude · Shift boost'}</div><button className="collection-count" onClick={()=>s.setPanel('map')}>✧ {s.progress.shards.length} / {SHARDS.length}<span>{zh?'星尘':'STARDUST'}</span></button></footer>
 {s.race&&<div className="race-hud"><span>{zh?'星环航线':'ORBITAL COURSE'}</span><strong>{s.raceTime.toFixed(1)}<small>s</small></strong><p>{s.checkpoint} / {RACE.length} {zh?'星环':'rings'}</p><div className="ring-direction"><span style={{transform:`rotate(${-ringBearing}rad)`}}>↑</span>{Math.round(Math.hypot(...checkpointPosition.map((v,i)=>v-s.position[i])))} {zh?'距离单位':'units'} · {Math.round(checkpointPosition[1]-s.position[1])>1?'↑':Math.round(checkpointPosition[1]-s.position[1])< -1?'↓':'—'}</div><button onClick={()=>s.update({race:false,checkpoint:0,raceTime:0})}>{zh?'结束挑战':'End run'}</button></div>}
 {notice&&<div className="space-toast" role="status">✧ {notice}</div>}
 {!s.panel&&!s.project&&<TouchControls lang={lang}/>}
 {!s.exploring&&(s.panel||s.project)&&<Modal atlas={s.panel==='map'&&!s.project} label={s.project?workFor(s.project,lang).name:s.panel==='map'?(zh?'星图':'Star chart'):s.panel==='experience'&&s.experience?pick(worldFor(s.experience)!.name,lang):s.panel==='help'?(zh?'飞行指南':'Flight guide'):(zh?'设置':'Settings')} onClose={()=>{s.setPanel(null);s.openProject(null);setConfirmReset(false)}}>
 <button className="space-modal-language" onClick={onLang}>{zh?'EN':'中文'}</button>
 {s.project?<><Project id={s.project} lang={lang}/><div className="space-modal-actions"><button onClick={()=>s.openExperience(projectWorld(s.project!)!.id)}>{zh?'返回经历':'Back to experience'}</button><button onClick={()=>{s.openProject(null);s.setPanel('map')}}>{zh?'返回星图':'Back to atlas'} ↗</button><button onClick={()=>s.openProject(null)}>{zh?'继续飞行':'Resume flight'}</button></div></>:s.panel==='experience'&&s.experience?<ExperiencePanel id={s.experience} lang={lang}/>:s.panel==='map'?<StarAtlas lang={lang}/>:s.panel==='help'?<Help lang={lang}/>:<><p className="space-eyebrow">{zh?'暂停航行':'FLIGHT PAUSED'}</p><h2>{zh?'在星空中，停留片刻。':'A moment among the stars.'}</h2><div className="space-settings"><button onClick={onLang}><span>{zh?'语言':'Language'}</span><strong>{zh?'中文 → English':'English → 中文'}</strong></button><button onClick={()=>s.update({sound:!s.sound})}><span>{zh?'环境声音':'Ambient sound'}</span><strong>{s.sound?(zh?'已开启':'On'):(zh?'已关闭':'Off')}</strong></button><button onClick={()=>s.update({reduced:!s.reduced})}><span>{zh?'动态效果':'Motion'}</span><strong>{s.reduced?(zh?'减少动态':'Reduced'):(zh?'跟随系统':'System preference')}</strong></button><button onClick={()=>s.update({low:!s.low})}><span>{zh?'画面质量':'Visual quality'}</span><strong>{s.low?(zh?'轻量':'Light'):(zh?'精细':'Detailed')}</strong></button><button onClick={()=>{s.update({resetFlight:s.resetFlight+1,destination:null,race:false,checkpoint:0,raceTime:0,panel:null,notice:'reset'})}}><span>{zh?'找不到方向？':'Lost in space?'}</span><strong>{zh?'返回起点 ↗':'Return to origin ↗'}</strong></button><button onClick={()=>{if(confirmReset){s.resetProgress();setConfirmReset(false)}else setConfirmReset(true)}}><span>{zh?'本机探索记录':'Local exploration record'}</span><strong>{confirmReset?(zh?'确认清空记录':'Confirm reset'):(zh?'重置进度':'Reset progress')}</strong></button></div><p className="space-modal-lead">{zh?'探索记录仅保存在当前浏览器。占位项目与模拟飞行数据不代表实际业务成果。':'Progress is stored only in this browser. Placeholder projects and simulated flight values are not business results.'}</p><div className="space-modal-actions"><button onClick={()=>s.setPanel(null)}>{zh?'继续飞行':'Resume flight'} ↗</button><button onClick={onExit}>{zh?'返回个人主页':'Return to portfolio'}</button></div></>}
 </Modal>}
 </div>
}
function THREEClamp(n:number,min:number,max:number){return Math.max(min,Math.min(max,n))}
